// ─── Telegram ────────────────────────────────────────────────────────────────
export async function sendTelegram(botToken, chatId, text) {
  const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
  const r = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      chat_id: chatId,
      text,
      parse_mode: 'HTML',
      disable_web_page_preview: false,
    }),
  });
  const d = await r.json();
  if (!d.ok) throw new Error(d.description || 'Telegram error');
  return d;
}

// Helper: Escape HTML special characters to avoid Telegram 400 bad request error
export function escapeHtml(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

export function formatTelegramMessage(cards, language) {
  const isZh = language === 'zh';
  const header = isZh
    ? `🔮 <b>CaféPrism 稜咖 每日摘要</b>\n${new Date().toLocaleDateString('zh-TW')}\n\n`
    : `🔮 <b>CaféPrism Daily Digest</b>\n${new Date().toDateString()}\n\n`;

  const body = cards.slice(0, 3).map((card, i) => {
    const badge = card.confidence === 'high' ? '🟢' : card.confidence === 'medium' ? '🟡' : '🔴';
    const rawTitle = card.primaryTitle || card.subject || (isZh ? '未命名研究' : 'Untitled Research');
    const title = escapeHtml(rawTitle.slice(0, 80));
    const cleanSummary = (card.summary || '').replace(/<[^>]+>/g, '').slice(0, 300);
    const summary = escapeHtml(cleanSummary);
    const rawLink = card.articles?.[0]?.link || '';
    const safeLink = (/^https?:\/\//i.test(rawLink) ? rawLink : '').replace(/&/g, '&amp;').replace(/"/g, '&quot;');
    const linkTag = safeLink ? `<a href="${safeLink}">${isZh ? '查看原文' : 'Read source'}</a>` : '';
    return `${badge} <b>${i + 1}. ${title}</b>\n${summary}...\n${linkTag}`;
  }).join('\n\n─────────────\n\n');

  const footer = isZh
    ? `\n\n<i>由 CaféPrism 稜咖 自動產生 · 每則摘要均附來源驗證</i>`
    : `\n\n<i>Generated by CaféPrism · Every claim is source-verified</i>`;

  return header + body + footer;
}
